=== pmd/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <element name="expected-problems" type="nonNegativeInteger"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code" type="string"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="" type="string">
                <annotation>
                    <documentation>
                        Language version of the source, eg 'java 8'.
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/UnconditionalIfStatement.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>if (true)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (true) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>if (false)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (false) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no constant folding</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    private static final boolean DEBUG = "false";
    void bar() {
        if (DEBUG) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>short circuit operator</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar(Object x, boolean y) {
        if (y == true) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#5882 false-negative if true/false is not literal but local variable</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
class UnconditionalIfStatementBug {
    public static void main(String[] args) {
        boolean condition = true;
        if (condition) {            // violation line 4
            System.out.println("This will always print.");
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#5882 false-negative if true/false is not literal but local variable negated</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
class UnconditionalIfStatementBug {
    public static void main(String[] args) {
        boolean condition = true;
        if (!condition) {            // violation line 4
            System.out.println("This will never print.");
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#5882 false-negative if true/false is not literal but local variable nested</description>
        <expected-problems>3</expected-problems>
        <expected-linenumbers>6,7,8</expected-linenumbers>
        <code><![CDATA[
class UnconditionalIfStatementBug {
    public static void main(String[] args) {
        boolean b1 = true;
        boolean b2 = false;
        boolean b3 = true;
        if (b1) {               // violation line 6
            if (!b2) {          // violation line 7
                if (b3) {       // violation line 8
                    System.out.println("This will always print.");
                }
            }
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#5882 false-positive if true/false is not literal but local variable modified</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
class UnconditionalIfStatementBug {
    public static void main(String[] args) {
        boolean condition = false;
        for (String arg : args) {
            if ("bar".equals(arg)) {
                condition |= true;
            }
        }
        if (condition) {
            System.out.println("bar was given.");
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#5882 false-positive if true/false is not literal but local variable not a literal</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
class UnconditionalIfStatementBug {
    public static void main(String[] args) {
        boolean condition = args.length == 0;
        if (condition) {
            System.out.println("No args given.");
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6435 false-negative if (!false)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (!false) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6435 false-negative if (!true)</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (!true) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6435 boolean literal with multiple logical negations</description>
        <expected-problems>4</expected-problems>
        <expected-linenumbers>3,4,5,6</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        if (!!true) {}
        if (!!!false) {}
        if (!!!!!!!!true) {}
        if (!((!!false))) {}
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6435 no false-positive for negated non-constant boolean</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar(boolean b) {
        if (!b) {}
        if (!!b) {}
        if (b) {
            boolean nested = !!!true;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#7060 Final local flags support conditional compilation</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
class Foo {
    void test() {
        final boolean enabled = true;
        if (enabled) {
            // Named constants allow conditional compilation.
        }
        final boolean disabled = false;
        if (!disabled) {
            // The same exclusion applies to negated constants.
        }
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/naming/xml/SuspiciousHashcodeMethodName.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <test-code>
        <description><![CDATA[
ok
     ]]></description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
 public int hashCode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
hashcode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int hashcode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
HashCode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int HashCode() {return 42;}
}
     ]]></code>
    </test-code>
    <test-code>
        <description><![CDATA[
Hashcode
     ]]></description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
 public int Hashcode() {return 42;}
}
     ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-apex/src/test/resources/net/sourceforge/pmd/lang/apex/rule/design/xml/NcssTypeCount.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>short</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        bar();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>lots of comments</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void foo() {
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        bar();
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        foo();
    }
}
        ]]></code>
    </test-code>

    <code-fragment id="long-method"><![CDATA[
public class Foo {
    public void foo() {
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        bar();
        bar();
        bar();
        bar();
        bar();
        bar();
        //nothing to see here
        //nothing to see here
        //nothing to see here
        //nothing to see here
        foo();
        foo();
        foo();
        foo();
        foo();
        foo();
    }
}
    ]]></code-fragment>

    <test-code>
        <description>long method</description>
        <rule-property name="minimum">13</rule-property>
        <expected-problems>1</expected-problems>
        <code-ref id="long-method"/>
    </test-code>

    <test-code>
        <description>long method - changed minimum</description>
        <!-- validated this number against NCSS -->
        <rule-property name="minimum">15</rule-property>
        <expected-problems>0</expected-problems>
        <code-ref id="long-method"/>
    </test-code>

    <test-code>
        <description>Github issue #251 - lines are counted properly</description>
        <rule-property name="minimum">10</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
@isTest
private class AcceptanceTests_Test {

    @isTest
    private static void test() {
        // Setup
        Opportunity o1 = new Opportunity()
                                    .add(new Contact().foo(1)  .bar(1).year(2012)  .bar(1).price(5)  .vol(100))
                                    .add(new Contact().foo(1)  .bar(2).year(2013)  .bar(1).price(5)  .vol(110))
                                    .add(new Contact().foo(1)  .bar(3).year(2014)  .bar(1).price(5)  .vol(120))
                                    .add(new Contact().foo(1)  .bar(4).year(2015)  .bar(1).price(5)  .vol(130))
                                    .persist();

        // Verify
        System.assert(attribute());
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1396 Method with comment</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
/**
 * Class comment
 */
public class SomeClass {
    /**
     * Comment
     */
    public void doSomething() {
        System.debug('hello world');
    }

    /** Field comment */
    private String field;
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/AvoidCatchingNPE.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>failure case</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>4</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (NullPointerException e) {
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>catching another type, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        try {
        } catch (FooException e) {
        }
    }
    public static class FooException extends NullPointerException {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>throwing it, ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        throw new NullPointerException();
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/performance/xml/UseStringBufferLength.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Using length properly</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <!-- Note: this changed in PMD 7. -->
        <description>StringBuffer.toString.equals(""), bad</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().equals("") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().equals("") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>StringBuffer.toString.equals("foo"), ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().equals("foo") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().equals("foo") ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>StringBuffer.toString.length(), bad</description>
        <expected-problems>2</expected-problems>
        <code><![CDATA[
public class Foo {
    void bar() {
        StringBuffer sb = new StringBuffer();
        if ( sb.toString().length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
    void bar2() {
        StringBuilder sb = new StringBuilder();
        if ( sb.toString().length() == 0 ) {
            sb.append(",");
        }
        sb.append( "whatever" );
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>no literals</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar(Object foo) {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals(foo);
    }
    boolean bar2(Object foo) {
        StringBuilder sb = new StringBuilder();
        return sb.toString().equals(foo);
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>empty + non-empty string sb.toString().equals("" + "x"), ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals("" + "x");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().trim().equals(""), ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer(" ");
        return sb.toString().trim().equals("");
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().equals(baz("")), ok</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().equals(baz(""));
    }
    String baz(String s) {
        return s + "x";
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>sb.toString().trim().length == 0, ok (as in: do not use StringBuffer.length())</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    boolean bar() {
        StringBuffer sb = new StringBuffer();
        return sb.toString().trim().length == 0;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1177 Incorrect StringBuffer warning when that class is not used</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Ineffecient
{
    public static String getValue(int in)
    {
        Integer i = new Integer(in);
        if (i.toString().length() == 1)
        {
            return "length 1";
        }
        return "";
    }

    public String toString()
    {
        return "Ineffecient";
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>[java] UseStringBufferLength: false negative with empty string variable #3639</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
public class Foo {
    public void foo() {
        StringBuffer sb = new StringBuffer("any_string");
        final String nullStr = "";
        if (sb.toString().equals(nullStr)) { // PMD should report a warning here
            System.out.println("Buffer is empty");
        }

        // the preferred way
        if (sb.length() == 0) {
            System.out.println("Buffer is empty");
        }
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-javascript/src/test/resources/net/sourceforge/pmd/lang/ecmascript/rule/performance/xml/AvoidConsoleStatements.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests https://pmd.github.io/schema/rule-tests_1_0_0.xsd">

    <test-code>
        <description>Any console method should be flagged</description>
        <expected-problems>9</expected-problems>
        <code><![CDATA[
console.log('foo');
console.error('foo');
console.info('foo');
console.warn('foo');
console.debug('foo');
console.trace('foo');
console.assert(false, 'foo');
console.dir(myObj);
console.group('label');
]]></code>
    </test-code>

    <test-code>
        <description>Any console method via window.console should be flagged</description>
        <expected-problems>9</expected-problems>
        <code><![CDATA[
window.console.log('foo');
window.console.error('foo');
window.console.info('foo');
window.console.warn('foo');
window.console.debug('foo');
window.console.trace('foo');
window.console.assert(false, 'foo');
window.console.dir(myObj);
window.console.group('label');
]]></code>
    </test-code>

    <test-code>
        <description>Other similar methods shouldn't be flagged</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
var MyFoo = {
    debug: function(a) {
        // ...
    },
    console: {
        debug: function(a) {
            // ...
        }
    }
};

MyFoo.debug('bar'); // ok, it is not console.debug
MyFoo.console.debug('bar'); // ok, it is not console.debug
]]></code>
    </test-code>
</test-data>
