=== pmd/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_0_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <element name="expected-problems" type="nonNegativeInteger"/>
            <element name="expected-linenumbers" type="string" minOccurs="0"/>
            <element name="expected-messages" minOccurs="0">
                <complexType>
                    <sequence>
                        <element name="message" type="string" maxOccurs="unbounded"/>
                    </sequence>
                </complexType>
            </element>
            <choice>
                <element name="code" type="string"/>
                <element name="code-ref">
                    <complexType>
                        <attribute name="id" type="IDREF" use="required"/>
                    </complexType>
                </element>
            </choice>
            <element name="source-type" minOccurs="0" default="" type="string">
                <annotation>
                    <documentation>
                        Language version of the source, eg 'java 8'.
                    </documentation>
                </annotation>
            </element>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codestyle/xml/UnnecessaryLocalBeforeReturn.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>skip void/native/abstract methods</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public void bar() {}
    public native int buz();
    public abstract int baz();
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip literal returns</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() { return 5; }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>simple failure case</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int x = doSomething();
        return x;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip complicated returns</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int x = doSomething();
        return x == null ? foo : bar;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>skip method calls</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        return doSomething(a, b, c);
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1495 [java] UnnecessaryLocalBeforeReturn with assert</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2; assert res>=0;
        return res;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#219 ClassCastException in switch case with local variable returned</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int m(int val) {
        switch (vl) {
            default:
                int i = 0;
                return i;
        }
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>Detect violation even if not on consecutive lines</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething();
        return res;
    }

    public void doSomething() { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>No violations on multiple uses of the variable</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething(res);
        return res;
    }

    public void doSomething(int x) { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>No violations on multiple uses of the variable - statement order does not matter</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    public int bar() {
        int res = 2;
        doSomething(res);
        return res;
    }

    public void doSomething(int x) { }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#933 UnnecessaryLocalBeforeReturn false positive for SuppressWarnings annotation</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class TestCase<T> {
    T getSomeT() { return null; }
    private static <T> T findEventTypeValueByName(TestCase<?> unchecked) {
        @SuppressWarnings("unchecked")
        T result = (T) unchecked.getSomeT();
        return result;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#282 UnnecessaryLocalBeforeReturn false positive when cloning Maps</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import java.util.HashMap;
public class CustomerErrorCollector {

    private final ConcurrentHashMap<String, String> customerErrors = new ConcurrentHashMap<>();

    public void error(String customerNr, String errorMsg) {
        customerErrors.put(customerNr, errorMsg);
    }

    public Map<String, String> getAndReset() {
        final Map<String, String> copy = new HashMap<>(customerErrors);
        customerErrors.clear();
        return copy; // PMD complains that variable could be avoided
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#310 UnnecessaryLocalBeforeReturn enhancement is overly restrictive -- method order matters</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Mutable {
    public int example1() {
        int i = compute(); // might throw
        markComputationDone();
        return i; // PMD complains that variable could be avoided
    }

    public int example2() {
        Mutable m = new Mutable();
        int i = compute(m);
        sideEffect(m);
        return i;
    }
    static void sideEffect(Mutable m) {}
    static int sideEffect(Mutable m) {}
    static int compute() {}
    static int markComputationDone() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#310 UnnecessaryLocalBeforeReturn statement order does not matter</description>
        <rule-property name="statementOrderMatters">false</rule-property>
        <expected-problems>2</expected-problems>
        <expected-linenumbers>3,10</expected-linenumbers>
        <code><![CDATA[
public class Mutable {
    public int example1() {
        int i = compute(); // might throw
        markComputationDone();
        return i; // PMD complains that variable could be avoided
    }

    public int example2() {
        Mutable m = new Mutable();
        int i = compute(m);
        sideEffect(m);
        return i;
    }
    static void sideEffect(Mutable m) {}
    static int sideEffect(Mutable m) {}
    static int compute() {}
    static int markComputationDone() {}
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1775 [java] False negative in UnnecessaryLocalBeforeReturn when splitting statements across multiple lines</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class UnnecessaryLocalBeforeReturnFP {
    public Object test2() {
        int i = 0;
        Object o = thing()
            .make(i);
        return o; // true positive
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#1804 [java] NPE with fields</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class ObjectCreator {

    private static final String A = "";
    private static final String B = "" + A; // the existence of this line causes the NPE.

    public Object create() {
        final Object o = new Object(A);
        return o;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FP with captured method reference</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import java.util.function.Supplier;
public class ObjectCreator {
    public Supplier<String> create() {
        final Object o = new Object(); // captured by the method ref
        return o::toString;
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FN with lambdas #3275</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>5</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Callable;

public class UnnecessaryLocal {
    void foo() {
        Callable<String> c = () -> { String s = "1"; return s; };
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>FN with anonymous classes #3275</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>7</expected-linenumbers>
        <code><![CDATA[
import java.util.concurrent.Callable;

public class UnnecessaryLocal {
    void foo() {
        Callable<String> c = new Callable<>() {
            public String call() {
                String s = "1";
                return s;
            }
        };
    }
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/bestpractices/xml/ReplaceVectorWithList.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>bad, local variable of type Vector</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;
public class Foo {
    void bar() {
        Vector v = new Vector();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>bad, param of type Vector</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;

public class Foo {
    void bar(Vector v) {
    }
}
        ]]></code>
    </test-code>


    <test-code>
        <description>Generic vector</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;

public class Foo {
    void bar(Vector<Integer> v) {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>ok, not java.util.Vector</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
import foo.Vector;

public class Foo {
    void bar(Vector v) {
    }
}
        ]]></code>
    </test-code>
    <test-code>
        <description>Not about vector</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
            package pmd.false_positive;

            import java.util.Map;
            import java.util.function.Predicate;

            public class AAntiFraudPolicy<C extends IAntiFraudCriterion> {

                public static <E extends Enum<E> & IAntiFraudCriterion> AAntiFraudPolicy<E> of(Class<E> enumClass,
                                                                                               Map<E, Predicate<AntiFraudCheckResult>> criterionChecks) {
                    return new AAntiFraudPolicy<E>();
                }

            }
        ]]></code>
    </test-code>

    <test-code>
        <description>#6546 declaration typed as Vector is a single violation</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;
public class Foo {
    void bar() {
        Vector v = new Vector();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6546 constructor is reported when the variable is not a Vector</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;
public class Foo {
    void bar() {
        Object v = new Vector();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6546 Stack is a Vector subclass and is reported once</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Deque;
import java.util.Stack;
public class Foo {
    void bar() {
        Deque s = new Stack();
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>#6546 extending Vector is still reported once</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
import java.util.Vector;
public class MyVec extends Vector {
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/errorprone/xml/CloneThrowsCloneNotSupportedException.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">

    <test-code>
        <description>ok, throws CloneNotSupportedException</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() throws CloneNotSupportedException {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>bad</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>final class, rule does not apply</description>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public final class Foo {
    void clone() {
    }
}
        ]]></code>
    </test-code>

    <test-code>
        <description>testing with multiple methods</description>
        <expected-problems>1</expected-problems>
        <code><![CDATA[
public class Foo {
    void clone() {}
    void foo() {}
    void bar() {}
}
        ]]></code>
    </test-code>
</test-data>

=== pmd/pmd/pmd-java/src/test/resources/net/sourceforge/pmd/lang/java/rule/codesize/xml/StdCyclomaticComplexity.xml
<?xml version="1.0" encoding="UTF-8"?>
<test-data
    xmlns="http://pmd.sourceforge.net/rule-tests"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">
    <code-fragment id="basic-violation">
    <![CDATA[
public class Foo {
 public void example() {
  int x = 0;
  int a = 0;
  int b = 0;
  int c = 0;
  int d = 0;
  int a1 = 0;
  int a2 = 0;
  int b1 = 0;
  int b2 = 0;
  int z = 0;
  int h = 0;
  int e = 0;
  int f = 0;

  if (a == b) {
      if (a1 == b1) {
   x = 2;
      } else if (a2 == b2) {
   x = 2;
      } else {
   x = 2;
      }
  } else if (c == d) {
      while (c == d) {
   x = 2;
      }
  } else if (e == f) {
      for (int n = 0; n < h; n++) {
   x = 2;
      }
  } else {
      switch (z) {
      case 1:
   x = 2;
   break;

      case 2:
   x = 2;
   break;

      case 3:
   x = 2;
   break;

      default:
   x = 2;
   break;
      }
  }
 }
}
     ]]>
    </code-fragment>
    <test-code>
        <description>Simple method</description>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 2 (Highest = 1).</message>
            <message>The method 'foo' has a Standard Cyclomatic Complexity of 1.</message>
        </expected-messages>
        <code><![CDATA[
public class Foo {
 public void foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Simple method</description>
        <rule-property name="reportLevel">10</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Foo {
 public void foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Complicated method</description>
        <rule-property name="reportLevel">10</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 12 (Highest = 11).</message>
            <message>The method 'example' has a Standard Cyclomatic Complexity of 11.</message>
        </expected-messages>
        <code-ref id="basic-violation"/>
    </test-code>
    <test-code>
        <description>Constructor</description>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>2</expected-problems>
        <expected-messages>
            <message>The class 'Foo' has a Standard Cyclomatic Complexity of 2 (Highest = 1).</message>
            <message>The constructor 'Foo' has a Standard Cyclomatic Complexity of 1.</message>
        </expected-messages>
        <code><![CDATA[
public class Foo {
 public Foo() {}
}
     ]]></code>
    </test-code>
    <test-code>
        <description>Testing new parameter showClassMethods</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <expected-problems>1</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
    <test-code>
        <description>Testing new parameter showMethodsMethods</description>
        <rule-property name="showMethodsComplexity">false</rule-property>
        <expected-problems>1</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
  <test-code>
        <description>Testing default value of showClassMethods and showClassesComplexity</description>
        <expected-problems>2</expected-problems>
       <code-ref id="basic-violation"/>
    </test-code>
    <code-fragment id="constructor-violation"><![CDATA[
public class Test {
  public Test() {
    if (a == 1) {
      if (b == 2) {
        System.out.println("b");
      } else if (b == 1) {
      }
    } else {
    }
  }
}
    ]]></code-fragment>
    <test-code>
        <description>#984 Cyclomatic complexity should treat constructors like methods: 1 - showMethodsComplexity=true</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <rule-property name="showMethodsComplexity">true</rule-property>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>1</expected-problems>
        <code-ref id="constructor-violation"/>
    </test-code>
    <test-code>
        <description>#984 Cyclomatic complexity should treat constructors like methods: 2 - showMethodsComplexity=false</description>
        <rule-property name="showClassesComplexity">false</rule-property>
        <rule-property name="showMethodsComplexity">false</rule-property>
        <rule-property name="reportLevel">1</rule-property>
        <expected-problems>0</expected-problems>
        <code-ref id="constructor-violation"/>
    </test-code>
    <test-code reinitializeRule="true">
        <description>#985 Suppressed methods shouldn't affect avg CyclomaticComplexity</description>
        <rule-property name="reportLevel">2</rule-property>
        <expected-problems>0</expected-problems>
        <code><![CDATA[
public class Test {
  @SuppressWarnings("PMD.StdCyclomaticComplexity")
  public Test() {
    if (a == 1) {
      if (b == 2) {
        System.out.println("b");
      } else if (b == 1) {
      }
    } else {
    }
  }
}
        ]]></code>
    </test-code>
</test-data>
